
include/wb_intercon_kuba.v: include/wb_intercon_kuba.conf
	../orpsoc-cores/cores/wb_intercon/sw/wb_intercon_gen $< $@ wb_intercon_kuba

clean:
	rm -f include/wb_intercon_kuba.v
	rm -f include/wb_intercon_kuba.vh
