set_property PACKAGE_PIN AE20 [get_ports areset_i]
set_property PACKAGE_PIN N4 [get_ports {qsfp_txp_o[0]}]
set_property PACKAGE_PIN M2 [get_ports {qsfp_txp_o[1]}]
set_property PACKAGE_PIN L4 [get_ports {qsfp_txp_o[2]}]
set_property PACKAGE_PIN P2 [get_ports {qsfp_txp_o[3]}]
set_property PACKAGE_PIN Y2 [get_ports {qsfp_txp_o[4]}]
set_property PACKAGE_PIN T2 [get_ports {qsfp_txp_o[5]}]
set_property PACKAGE_PIN V2 [get_ports {qsfp_txp_o[6]}]
set_property PACKAGE_PIN U4 [get_ports {qsfp_txp_o[7]}]
set_property PACKAGE_PIN AK21 [get_ports resetdone_o]
set_property IOSTANDARD LVCMOS33 [get_ports areset_i]
set_property IOSTANDARD LVCMOS33 [get_ports resetdone_o]
set_property PACKAGE_PIN L8 [get_ports qsfp_refclk_p_i]

