#
# Vivado (TM) v2014.2 (64-bit)
#
# mexiko.tcl: Tcl script for re-creating project 'mexiko'
#
# Generated by Vivado on Fri Jul 04 10:41:29 IST 2014
# IP Build 924643 on Fri May 30 09:20:16 MDT 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (mexiko.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cache_lru.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/raminfr.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncflop.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx-defines.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx-sprs.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_ticktimer.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_store_buffer.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_rf_ram.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_pic.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_immu.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_icache.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_dmmu.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_dcache.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cfgrs.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/include/uart_defines.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_tfifo.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_rfifo.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncreg.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/bytefifo.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_rf_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_lsu_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_fetch_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_execute_alu.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_decode.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_branch_prediction.v"
#    "/home/bluecmd/work/mexiko/rtl/utils/ff_syncer.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/verilog-arbiter/src/arbiter.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_transmitter.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/timescale.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_sync_flops.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_receiver.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_defines.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_biu.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_defines.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_status_reg.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_biu.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_biu.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_crc32.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cpu_espresso.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v"
#    "/home/bluecmd/work/mexiko/rtl/xilinx/xilinx_phy10g_shared_logic.sv"
#    "/home/bluecmd/work/mexiko/rtl/xilinx/xilinx_phy10g_quad_logic.sv"
#    "/home/bluecmd/work/mexiko/rtl/xilinx/xilinx_lane.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/verilog_utils/verilog_utils.vh"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/wb_intercon/wb_mux.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/wb_intercon/wb_data_resize.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/wb_intercon/wb_arbiter.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_wb.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_regs.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_defines.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_module.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_module.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_module.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_cpu.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx_bus_if_avalon.v"
#    "/home/bluecmd/work/mexiko/rtl/xilinx/xilinx_octa10g.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/rom.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/include/wb_intercon.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/clkgen.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_top.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_top.v"
#    "/home/bluecmd/work/mexiko/rtl/mor1kx/rtl/verilog/mor1kx.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/include/wb_intercon.vh"
#    "/home/bluecmd/work/mexiko/rtl/mexiko-defs.vh"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc/orpsoc.sv"
#    "/home/bluecmd/work/mexiko/rtl/network.sv"
#    "/home/bluecmd/work/mexiko/rtl/mexiko.sv"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/uart16550/rtl/verilog/uart_defines.v"
#    "/home/bluecmd/work/mexiko/rtl/vivado/mexiko.srcs/sources_1/ip/xilinx_phy10g/xilinx_phy10g.upgrade_log"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/ram_wb/ram_wb_b3.v"
#    "/home/bluecmd/work/mexiko/rtl/orpsoc-cores/cores/ram_wb/ram_wb.v"
#    "/home/bluecmd/.cache/fusesoc/i2c/i2c_master_defines.v"
#    "/home/bluecmd/.cache/fusesoc/i2c/i2c_master_bit_ctrl.v"
#    "/home/bluecmd/.cache/fusesoc/i2c/i2c_master_top.v"
#    "/home/bluecmd/.cache/fusesoc/i2c/i2c_master_byte_ctrl.v"
#    "/home/bluecmd/work/mexiko/rtl/vivado/mexiko.srcs/sources_1/ip/xilinx_phy10g/xilinx_phy10g.xci"
#    "/home/bluecmd/work/mexiko/rtl/xdc/htgk700.xdc"
#    "/home/bluecmd/work/mexiko/rtl/xdc/xilinx_phy10g.xdc"
#    "/home/bluecmd/work/mexiko/rtl/xdc/orpsoc.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project mexiko ./mexiko

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects mexiko]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7k325tffg900-2" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cache_lru.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/raminfr.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncflop.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx-defines.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx-sprs.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ticktimer.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_store_buffer.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_ram.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_pic.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_immu.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_icache.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_dmmu.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_dcache.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cfgrs.v"]"\
 "[file normalize "$origin_dir/../orpsoc/include/uart_defines.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_tfifo.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_rfifo.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncreg.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/bytefifo.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_lsu_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_execute_alu.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_decode.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_branch_prediction.v"]"\
 "[file normalize "$origin_dir/../utils/ff_syncer.sv"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/verilog-arbiter/src/arbiter.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_transmitter.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/timescale.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_sync_flops.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_receiver.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_defines.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_biu.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_defines.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_status_reg.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_biu.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_biu.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_crc32.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_espresso.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v"]"\
 "[file normalize "$origin_dir/../xilinx/xilinx_phy10g_shared_logic.sv"]"\
 "[file normalize "$origin_dir/../xilinx/xilinx_phy10g_quad_logic.sv"]"\
 "[file normalize "$origin_dir/../xilinx/xilinx_lane.sv"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/verilog_utils/verilog_utils.vh"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/wb_intercon/wb_mux.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/wb_intercon/wb_data_resize.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/wb_intercon/wb_arbiter.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_wb.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_regs.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_defines.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_module.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_module.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_module.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx_bus_if_avalon.v"]"\
 "[file normalize "$origin_dir/../xilinx/xilinx_octa10g.sv"]"\
 "[file normalize "$origin_dir/../orpsoc/rom.sv"]"\
 "[file normalize "$origin_dir/../orpsoc/include/wb_intercon.v"]"\
 "[file normalize "$origin_dir/../orpsoc/clkgen.sv"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_top.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_top.v"]"\
 "[file normalize "$origin_dir/../mor1kx/rtl/verilog/mor1kx.v"]"\
 "[file normalize "$origin_dir/../orpsoc/include/wb_intercon.vh"]"\
 "[file normalize "$origin_dir/../mexiko-defs.vh"]"\
 "[file normalize "$origin_dir/../orpsoc/orpsoc.sv"]"\
 "[file normalize "$origin_dir/../network.sv"]"\
 "[file normalize "$origin_dir/../mexiko.sv"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_defines.v"]"\
 "[file normalize "$origin_dir/mexiko.srcs/sources_1/ip/xilinx_phy10g/xilinx_phy10g.upgrade_log"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/ram_wb/ram_wb_b3.v"]"\
 "[file normalize "$origin_dir/../orpsoc-cores/cores/ram_wb/ram_wb.v"]"\
 "[file normalize "$origin_dir/../../../../.cache/fusesoc/i2c/i2c_master_defines.v"]"\
 "[file normalize "$origin_dir/../../../../.cache/fusesoc/i2c/i2c_master_bit_ctrl.v"]"\
 "[file normalize "$origin_dir/../../../../.cache/fusesoc/i2c/i2c_master_top.v"]"\
 "[file normalize "$origin_dir/../../../../.cache/fusesoc/i2c/i2c_master_byte_ctrl.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/raminfr.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncflop.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx-defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx-sprs.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ticktimer.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_store_buffer.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_ram.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_pic.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_immu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_icache.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_dmmu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_dcache.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cfgrs.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_tfifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_rfifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/syncreg.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/bytefifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_lsu_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_execute_alu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_decode.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_branch_prediction.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../utils/ff_syncer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/verilog-arbiter/src/arbiter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "wishbone" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_transmitter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/timescale.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_sync_flops.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_receiver.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_biu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_status_reg.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_biu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_biu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_crc32.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_espresso.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../xilinx/xilinx_phy10g_shared_logic.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../xilinx/xilinx_phy10g_quad_logic.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../xilinx/xilinx_lane.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/verilog_utils/verilog_utils.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/wb_intercon/wb_data_resize.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "wishbone" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/wb_intercon/wb_arbiter.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "wishbone" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_wb.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_regs.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_wb_module.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_or1k_module.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_jsp_module.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_cpu.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx_bus_if_avalon.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../xilinx/xilinx_octa10g.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc/rom.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc/include/wb_intercon.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "wishbone" $file_obj

set file "$origin_dir/../orpsoc/clkgen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_top.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/adv_debug_sys/rtl/verilog/adbg_top.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "adbg" $file_obj

set file "$origin_dir/../mor1kx/rtl/verilog/mor1kx.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "mor1kx" $file_obj

set file "$origin_dir/../orpsoc/include/wb_intercon.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/../mexiko-defs.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "$origin_dir/../orpsoc/orpsoc.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../network.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../mexiko.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj

set file "$origin_dir/../orpsoc-cores/cores/uart16550/rtl/verilog/uart_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "library" "uart" $file_obj

set file "$origin_dir/mexiko.srcs/sources_1/ip/xilinx_phy10g/xilinx_phy10g.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "mexiko" $obj

# Create 'xilinx_ddr3' fileset (if not found)
if {[string equal [get_filesets -quiet xilinx_ddr3] ""]} {
  create_fileset -blockset xilinx_ddr3
}

# Set 'xilinx_ddr3' fileset object
set obj [get_filesets xilinx_ddr3]
# Empty (no sources present)

# Set 'xilinx_ddr3' fileset properties
set obj [get_filesets xilinx_ddr3]
set_property "top" "xilinx_ddr3" $obj

# Create 'xilinx_pcie1x' fileset (if not found)
if {[string equal [get_filesets -quiet xilinx_pcie1x] ""]} {
  create_fileset -blockset xilinx_pcie1x
}

# Set 'xilinx_pcie1x' fileset object
set obj [get_filesets xilinx_pcie1x]
# Empty (no sources present)

# Set 'xilinx_pcie1x' fileset properties
set obj [get_filesets xilinx_pcie1x]
set_property "top" "xilinx_pcie1x" $obj

# Create 'xilinx_phy10g' fileset (if not found)
if {[string equal [get_filesets -quiet xilinx_phy10g] ""]} {
  create_fileset -blockset xilinx_phy10g
}

# Set 'xilinx_phy10g' fileset object
set obj [get_filesets xilinx_phy10g]
set files [list \
 "[file normalize "$origin_dir/mexiko.srcs/sources_1/ip/xilinx_phy10g/xilinx_phy10g.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'xilinx_phy10g' fileset file properties for remote files
# None

# Set 'xilinx_phy10g' fileset file properties for local files
# None

# Set 'xilinx_phy10g' fileset properties
set obj [get_filesets xilinx_phy10g]
set_property "top" "xilinx_phy10g" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../xdc/htgk700.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../xdc/htgk700.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../xdc/xilinx_phy10g.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../xdc/xilinx_phy10g.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "processing_order" "EARLY" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../xdc/orpsoc.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../xdc/orpsoc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/../xdc/htgk700.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "mexiko" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2013" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_ddr3_synth_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_ddr3_synth_1] ""]} {
  create_run -name xilinx_ddr3_synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset xilinx_ddr3
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs xilinx_ddr3_synth_1]
  set_property flow "Vivado Synthesis 2013" [get_runs xilinx_ddr3_synth_1]
}
set obj [get_runs xilinx_ddr3_synth_1]
set_property "constrset" "xilinx_ddr3" $obj
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_pcie1x_synth_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_pcie1x_synth_1] ""]} {
  create_run -name xilinx_pcie1x_synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset xilinx_pcie1x
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs xilinx_pcie1x_synth_1]
  set_property flow "Vivado Synthesis 2013" [get_runs xilinx_pcie1x_synth_1]
}
set obj [get_runs xilinx_pcie1x_synth_1]
set_property "constrset" "xilinx_pcie1x" $obj
set_property "needs_refresh" "1" $obj
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_phy10g_synth_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_phy10g_synth_1] ""]} {
  create_run -name xilinx_phy10g_synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset xilinx_phy10g
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs xilinx_phy10g_synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs xilinx_phy10g_synth_1]
}
set obj [get_runs xilinx_phy10g_synth_1]
set_property "constrset" "xilinx_phy10g" $obj
set_property "part" "xc7k325tffg900-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2013" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_ddr3_impl_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_ddr3_impl_1] ""]} {
  create_run -name xilinx_ddr3_impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset xilinx_ddr3 -parent_run xilinx_ddr3_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs xilinx_ddr3_impl_1]
  set_property flow "Vivado Implementation 2013" [get_runs xilinx_ddr3_impl_1]
}
set obj [get_runs xilinx_ddr3_impl_1]
set_property "constrset" "xilinx_ddr3" $obj
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_pcie1x_impl_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_pcie1x_impl_1] ""]} {
  create_run -name xilinx_pcie1x_impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset xilinx_pcie1x -parent_run xilinx_pcie1x_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs xilinx_pcie1x_impl_1]
  set_property flow "Vivado Implementation 2013" [get_runs xilinx_pcie1x_impl_1]
}
set obj [get_runs xilinx_pcie1x_impl_1]
set_property "constrset" "xilinx_pcie1x" $obj
set_property "part" "xc7k325tffg900-2" $obj

# Create 'xilinx_phy10g_impl_1' run (if not found)
if {[string equal [get_runs -quiet xilinx_phy10g_impl_1] ""]} {
  create_run -name xilinx_phy10g_impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset xilinx_phy10g -parent_run xilinx_phy10g_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs xilinx_phy10g_impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs xilinx_phy10g_impl_1]
}
set obj [get_runs xilinx_phy10g_impl_1]
set_property "constrset" "xilinx_phy10g" $obj
set_property "part" "xc7k325tffg900-2" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:mexiko"
