#!/usr/bin/env python2
from functools import partial
import binascii
import sys

with open(sys.argv[1], 'rb') as infile:
  for word in iter(partial(infile.read, 4), ''):
    print binascii.hexlify(word)
