#!/usr/bin/env python2
from functools import partial
import struct
import sys

with open(sys.argv[1]) as infile:
  for short in iter(partial(infile.read, 2), ''):
    sys.stdout.write(short[1] if len(short) > 1 else chr(0))
    sys.stdout.write(short[0])
